/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.inventarioController;
import javax.swing.JOptionPane;
import model.inventario;
import views.frmAdminProductos;


/**
 *
 * @author felip
 */
public class dlgCrearProducto extends javax.swing.JDialog {

    /**
     * Creates new form dlgCrearProducto
     */
    public dlgCrearProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(400, 400);
        setTitle("Crear Producto");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnanadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        jpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));
        jpanel.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        jLabel2.setText("Marca");
        jpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, -1));
        jpanel.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, -1));
        jpanel.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, -1));

        jLabel3.setText("Precio");
        jpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));

        jLabel4.setText("Cantidad");
        jpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));
        jpanel.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, -1));

        btnanadir.setText("añadir");
        btnanadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanadirActionPerformed(evt);
            }
        });
        jpanel.add(btnanadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 100, 40));

        getContentPane().add(jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnanadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanadirActionPerformed


        //obtiene el texto
        String nombre = txtNombre.getText();
        String marca = txtMarca.getText();
        String precioTexto = txtPrecio.getText();
        String cantidadTexto = txtCantidad.getText();
        
        int precio = Integer.parseInt(precioTexto);
        int cantidad = Integer.parseInt(cantidadTexto);

        // 2. Crear objeto inventario
        inventario inventario = new inventario();
        inventario.setNombre(nombre);
        inventario.setMarca(marca);
        inventario.setPrecio(precio);
        inventario.setCantidad(cantidad);
        

        // 3. Llamar al controlador
        inventarioController inventarioControlador = new inventarioController();
        boolean creado = inventarioControlador.crearProducto(inventario);

        if (creado) {
            JOptionPane.showMessageDialog(this, "Producto creado correctamente");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear Producto", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_btnanadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgCrearProducto dialog = new dlgCrearProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpanel;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
